/**
 * Renders the generator's parameter tables for the README straight from src/generator/params.ts:
 * the values come from DEFAULT_PARAMS and the meanings from the doc comments on GeneratorParams,
 * so the documentation cannot drift from the code. `npm run check` fails when the README block is stale;
 * `npm run check -- --write-docs` rewrites it.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import ts from 'typescript';
import { DEFAULT_PARAMS, type GeneratorParams } from '../../src/generator/params';
import { ROOT } from './node-data';

const PARAMS_FILE = join(ROOT, 'src', 'generator', 'params.ts');

export const DOCS_BEGIN = '<!-- params:begin (generated by `npm run check -- --write-docs`, do not edit by hand) -->';
export const DOCS_END = '<!-- params:end -->';

interface Member {
  text: string;
  section: string | null;
}

/** "Interface.member" (and "Interface.member.nested") -> doc comment text and the "// ----" section it sits in. */
function readMembers(): Map<string, Member> {
  const source = readFileSync(PARAMS_FILE, 'utf8');
  const sf = ts.createSourceFile(PARAMS_FILE, source, ts.ScriptTarget.Latest, true);
  const out = new Map<string, Member>();
  const docText = (node: ts.Node): string => {
    const d = ts.getJSDocCommentsAndTags(node).find(ts.isJSDoc);
    return d ? (ts.getTextOfJSDocComment(d.comment) ?? '').replace(/\s+/g, ' ').trim() : '';
  };
  const walk = (prefix: string, members: ts.NodeArray<ts.TypeElement>): void => {
    let section: string | null = null;
    for (const m of members) {
      if (!ts.isPropertySignature(m) || !m.name) continue;
      for (const r of ts.getLeadingCommentRanges(source, m.getFullStart()) ?? []) {
        const hit = /^\/\/\s*-{2,}\s*(.+)$/.exec(source.slice(r.pos, r.end));
        if (hit) section = hit[1].trim();
      }
      const path = `${prefix}.${m.name.getText(sf)}`;
      out.set(path, { text: docText(m), section });
      if (m.type && ts.isTypeLiteralNode(m.type)) walk(path, m.type.members);
    }
  };
  sf.forEachChild((node) => {
    if (ts.isInterfaceDeclaration(node)) walk(node.name.text, node.members);
  });
  return out;
}

const fmt = (v: unknown): string => (Array.isArray(v) ? `[${v.join(', ')}]` : String(v));
const cell = (s: string): string => s.replace(/\|/g, '\\|');

export function renderParamDocs(params: GeneratorParams = DEFAULT_PARAMS): string {
  const docs = readMembers();
  const doc = (path: string): string => {
    const d = docs.get(path)?.text;
    if (!d) throw new Error(`params.ts: "${path}" has no doc comment, so it cannot appear in the README`);
    return d;
  };
  const lines: string[] = [];

  // ---- scalar parameters, grouped by the "// ----" sections in params.ts
  const scalarRows = new Map<string, string[]>();
  const addScalar = (path: string, value: unknown, docPath: string): void => {
    const section = docs.get(`GeneratorParams.${path.split('.')[0]}`)?.section ?? 'other';
    if (!scalarRows.has(section)) scalarRows.set(section, []);
    scalarRows.get(section)!.push(`| \`${path}\` | ${fmt(value)} | ${cell(doc(docPath))} |`);
  };
  const structured = new Set(['plan', 'phaseWeights', 'styles']);
  for (const [key, value] of Object.entries(params)) {
    if (structured.has(key)) continue;
    if (key === 'phaseWindowS') {
      for (const [phase, win] of Object.entries(value as Record<string, number[]>)) addScalar(`phaseWindowS.${phase}`, win, 'GeneratorParams.phaseWindowS');
    } else if (value && typeof value === 'object') {
      for (const [k, v] of Object.entries(value as Record<string, unknown>)) addScalar(`${key}.${k}`, v, `GeneratorParams.${key}.${k}`);
    } else {
      addScalar(key, value, `GeneratorParams.${key}`);
    }
  }
  for (const [section, rows] of scalarRows) {
    lines.push(`**${section[0].toUpperCase()}${section.slice(1)}**`, '', '| Parameter | Default | Meaning |', '| --- | --- | --- |', ...rows, '');
  }

  // ---- per-phase evidence weights (a matrix: phase x term)
  const phases = Object.keys(params.phaseWeights);
  const terms = Object.keys(params.phaseWeights[phases[0] as keyof typeof params.phaseWeights]);
  lines.push('**Score term weights per game phase** (`phaseWeights`)', '', `| Phase | ${terms.map((t) => `\`${t}\``).join(' | ')} |`, `| --- |${terms.map(() => ' ---:').join(' |')} |`);
  for (const ph of phases) {
    const w = params.phaseWeights[ph as keyof typeof params.phaseWeights] as unknown as Record<string, number>;
    lines.push(`| ${ph} | ${terms.map((t) => w[t]).join(' | ')} |`);
  }
  lines.push('');
  for (const t of terms) lines.push(`- \`${t}\`: ${doc(`PhaseWeights.${t}`)}`);
  lines.push('');

  // ---- phase plan
  const planKeys = Object.keys(params.plan[0]);
  lines.push('**Phase plan** (`plan`)', '', `| ${planKeys.map((k) => `\`${k}\``).join(' | ')} |`, `|${planKeys.map(() => ' --- ').join('|')}|`);
  for (const step of params.plan) lines.push(`| ${planKeys.map((k) => (step as unknown as Record<string, unknown>)[k]).join(' | ')} |`);
  lines.push('');
  for (const k of planKeys.filter((x) => x !== 'phase')) lines.push(`- \`${k}\`: ${doc(`PhasePlanStep.${k}`)}`);
  lines.push('');

  // ---- build styles
  const styleKeys = ['aGun', 'aSpirit', 'aSurv', 'aUtil'] as const;
  const slots = Object.keys(params.styles[0].slotBias);
  lines.push('**Build styles** (`styles`)', '', `| Style | ${styleKeys.map((k) => `\`${k}\``).join(' | ')} | ${slots.map((s) => `\`slotBias.${s}\``).join(' | ')} |`, `| --- |${[...styleKeys, ...slots].map(() => ' ---:').join(' |')} |`);
  for (const s of params.styles) {
    lines.push(`| ${s.id} | ${styleKeys.map((k) => s[k]).join(' | ')} | ${slots.map((sl) => s.slotBias[sl as keyof typeof s.slotBias]).join(' | ')} |`);
  }
  lines.push('');
  for (const k of [...styleKeys, 'slotBias']) lines.push(`- \`${k}\`: ${doc(`StyleDef.${k}`)}`);
  lines.push('');

  return lines.join('\n').trimEnd();
}

/** The README text with the generated block replaced (or appended markers inserted by hand beforehand). */
export function withParamDocs(readme: string, block: string): string {
  const a = readme.indexOf(DOCS_BEGIN);
  const b = readme.indexOf(DOCS_END);
  if (a < 0 || b < a) throw new Error('README.md has no params:begin / params:end markers');
  return `${readme.slice(0, a + DOCS_BEGIN.length)}\n\n${block}\n\n${readme.slice(b)}`;
}
